services:
    tatiana5.editor_of_attachments.listener:
        class: tatiana5\editor_of_attachments\event\listener
        arguments:
            - @auth
            - @config
            - @template
            - @user
            - @dbal.conn
            - %core.root_path%
            - %core.php_ext%
            - @tatiana5.editor_of_attachments.watermark
        tags:
            - { name: event.listener }
    tatiana5.editor_of_attachments.watermark:
        class: tatiana5\editor_of_attachments\core\watermark
        arguments:
            - @config
